cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED DOL OR DOL STREQUAL "")
    message(FATAL_ERROR "DOL path is required")
endif()
if(NOT EXISTS "${DOL}")
    message(FATAL_ERROR "DOL does not exist: ${DOL}")
endif()

file(SIZE "${DOL}" dol_size)
if(dol_size LESS 228)
    message(FATAL_ERROR "DOL header is truncated: ${DOL}")
endif()

function(read_dol_u32 offset output)
    file(READ "${DOL}" value_hex OFFSET ${offset} LIMIT 4 HEX)
    string(LENGTH "${value_hex}" value_length)
    if(NOT value_length EQUAL 8 OR NOT value_hex MATCHES "^[0-9A-Fa-f]+$")
        message(FATAL_ERROR "Invalid DOL header word at offset ${offset}: '${value_hex}'")
    endif()
    math(EXPR value "0x${value_hex}")
    set(${output} ${value} PARENT_SCOPE)
endfunction()

set(highest 0)

foreach(index RANGE 0 6)
    math(EXPR address_offset "0x48 + ${index} * 4")
    math(EXPR size_offset "0x90 + ${index} * 4")
    read_dol_u32(${address_offset} section_address)
    read_dol_u32(${size_offset} section_size)
    if("${section_size}" GREATER 0)
        math(EXPR section_end "${section_address} + ${section_size}")
        if(section_end GREATER highest)
            set(highest ${section_end})
        endif()
    endif()
endforeach()

foreach(index RANGE 0 10)
    math(EXPR address_offset "0x64 + ${index} * 4")
    math(EXPR size_offset "0xac + ${index} * 4")
    read_dol_u32(${address_offset} section_address)
    read_dol_u32(${size_offset} section_size)
    if("${section_size}" GREATER 0)
        math(EXPR section_end "${section_address} + ${section_size}")
        if(section_end GREATER highest)
            set(highest ${section_end})
        endif()
    endif()
endforeach()

read_dol_u32(216 bss_address)
read_dol_u32(220 bss_size)
if("${bss_size}" GREATER 0)
    math(EXPR bss_end "${bss_address} + ${bss_size}")
    if(bss_end GREATER highest)
        set(highest ${bss_end})
    endif()
endif()

set(production_limit 0x80900000)
set(required_headroom 0x00004000)
math(EXPR safe_limit "${production_limit} - ${required_headroom}")
math(EXPR highest_hex "${highest}" OUTPUT_FORMAT HEXADECIMAL)
math(EXPR production_limit_hex "${production_limit}" OUTPUT_FORMAT HEXADECIMAL)
if(highest GREATER safe_limit)
    message(FATAL_ERROR
        "DOL load layout exceeds the production MEM1 safety margin: "
        "highest=${highest_hex} limit=${production_limit_hex} headroom=16KB")
endif()

math(EXPR headroom_bytes "${production_limit} - ${highest}")
math(EXPR headroom_kib "${headroom_bytes} / 1024")
message(STATUS "DOL layout OK: highest=${highest_hex} headroom=${headroom_kib}KB")
